<a href="https://colab.research.google.com/github/Moutata6/DS1002-Moutata6/blob/main/homework/week-7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 7

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

Load the following dataset into pandas and perform the requested operations in code.

Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [1]:
# Load pandas and the data
import pandas as pd
df = pd.read_csv('https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv')

In [2]:
# show how many rows and columns are in this dataset
df.shape

(25760, 10)

In [3]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)
df['duration'] = df['duration'].str.strip("minutes")
df['duration'] = df['duration'].astype('int')

In [4]:
# Now display the datatypes in the updated dataframe
df.dtypes

duration            int64
station_A_id        int64
station_A_name     object
station_B_id        int64
station_B_name     object
bike_id             int64
user_type           int64
user_birth_year     int64
user_gender        object
tire_size           int64
dtype: object

In [6]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.
df['duration'].min()
df['duration'].max()

1372

In [11]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
df2 = df[df.duration <= 60]

In [12]:
# Now show both the min and max values of the duration column for your new dataset.
df2['duration'].min()
df2['duration'].max()

60

In [15]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
df3 = df2[df2.tire_size == 26]

In [20]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
df4 = df3[df3.user_gender == "Female"]
len(df4)
df4.head(30)

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
18,16,16,Steuart St at Market St,42,San Francisco City Hall (Polk St at Grove St),5000,2,2000,Female,26
41,12,3,Powell St BART Station (Market St at 4th St),6,The Embarcadero at Sansome St,2899,1,1967,Female,26
45,1,67,San Francisco Caltrain Station 2 (Townsend St...,64,5th St at Brannan St,2436,2,1990,Female,26
52,13,21,Montgomery St BART Station (Market St at 2nd St),78,Folsom St at 9th St,2531,2,1999,Female,26
53,14,21,Montgomery St BART Station (Market St at 2nd St),78,Folsom St at 9th St,1502,2,1998,Female,26
57,11,21,Montgomery St BART Station (Market St at 2nd St),61,Howard St at 8th St,2918,2,1999,Female,26
75,11,21,Montgomery St BART Station (Market St at 2nd St),58,Market St at 10th St,316,2,1999,Female,26
76,18,22,Howard St at Beale St,72,Page St at Scott St,5162,2,1980,Female,26
88,6,81,Berry St at 4th St,130,22nd St Caltrain Station,5224,2,1983,Female,26
89,11,3,Powell St BART Station (Market St at 4th St),58,Market St at 10th St,192,2,2000,Female,26
93,9,3,Powell St BART Station (Market St at 4th St),58,Market St at 10th St,1465,1,1999,Female,26
94,9,3,Powell St BART Station (Market St at 4th St),58,Market St at 10th St,685,1,1991,Female,26
95,10,3,Powell St BART Station (Market St at 4th St),58,Market St at 10th St,3109,1,2000,Female,26
107,5,3,Powell St BART Station (Market St at 4th St),16,Steuart St at Market St,593,2,2000,Female,26
117,8,5,Powell St BART Station (Market St at 5th St),47,4th St at Harrison St,5474,2,1997,Female,26
142,8,5,Powell St BART Station (Market St at 5th St),74,Laguna St at Hayes St,4968,2,1993,Female,26
155,13,30,San Francisco Caltrain (Townsend St at 4th St),136,23rd St at San Bruno Ave,5574,2,1980,Female,26
160,21,81,Berry St at 4th St,55,Webster St at Grove St,4969,2,1969,Female,26
161,7,5,Powell St BART Station (Market St at 5th St),43,San Francisco Public Library (Grove St at Hyde...,5530,3,1990,Female,26
167,8,30,San Francisco Caltrain (Townsend St at 4th St),5,Powell St BART Station (Market St at 5th St),4968,2,1993,Female,26
177,16,67,San Francisco Caltrain Station 2 (Townsend St...,55,Webster St at Grove St,4953,1,1992,Female,26
184,19,5,Powell St BART Station (Market St at 5th St),144,Precita Park,4553,1,1994,Female,26
207,14,15,San Francisco Ferry Building (Harry Bridges Pl...,116,Mississippi St at 17th St,5463,3,1988,Female,26
219,14,67,San Francisco Caltrain Station 2 (Townsend St...,109,17th St at Valencia St,5029,1,1988,Female,26
220,10,15,San Francisco Ferry Building (Harry Bridges Pl...,30,San Francisco Caltrain (Townsend St at 4th St),2960,2,1991,Female,26
227,26,22,Howard St at Beale St,120,Mission Dolores Park,3053,2,1987,Female,26
251,10,81,Berry St at 4th St,87,Folsom St at 13th St,5369,2,1984,Female,26
261,10,21,Montgomery St BART Station (Market St at 2nd St),8,The Embarcadero at Vallejo St,1544,3,1991,Female,26
263,6,5,Powell St BART Station (Market St at 5th St),58,Market St at 10th St,2436,2,1987,Female,26
268,11,22,Howard St at Beale St,67,San Francisco Caltrain Station 2 (Townsend St...,5536,1,1982,Female,26